### ISSUE TITLE
Invoice Status Pending / Paid

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#13]
I tried to find a way to set invoices which got captured to "paid" and changed
magento2-wcs\Model\OrderManagement.php #339   
$doCapture = true;

it works in 80% of the cases but not on all. Some invoices I still have to capture manually. Any suggestions?

**Comment by jakubpolomsky** [comment]
Hello and thank you for your input.

The logic behind the invoice capturing has the following logic.

 Was the order already processed? If not, check the payment state. 
Payment pending? DO NOT CAPTURE
Otherwise prepare invoice. Are backend operations allowed? CAPTURE
Otherwise DO NOT CAPTURE

So you can check the scenarios and pick the corresponding one. Hard coding the capture is not the correct solution and it only fools the shop. Payment itself doesn't necessarily need to be processed so I'd leave the logic as it is.

Kind regards

**Comment by marcmayo** [comment]
@jakubpolomsky the problem is that it doesn't automatically get captured once the payment is made?
The invoices stay "pending" even tho the capture has gone through on wirecard because wirecard doesn't send an update once the capture was successful

**Comment by jakubpolomsky** [comment]
Well it can be a problem if I know how to reproduce the behavior you are claiming. Then please, following the steps I wrote, tell me which point isn't doing what it is supposed to. Take a look at every each of the points. That is the logic (simple logic) behind the capture of an invoice. It works on every of our test stystems flawlessly. The error can be only in one (or more) of the steps.

**Comment by rinnhofer** [comment]
Hello,
we did some updates including the capturing process for deposit payments.
If you use automated deposit the invoices get now captured and some checks got removed. Please do not change $doCapture hard coded. The logic behind the capturing should be as it is now:
Successfull payment -> has backend operations -> backend operation "DEPOSIT" already done? -> CAPTURE. 

If have any further questions please open a new issue or contact <support.at@wirecard.com> for help.

Cheers
